### ISSUE TITLE
Unhanded 'error' event...

### ISSUE THREAD

**Issue by CharlesHBS** [guerrerocarlos/bitcoin-receive-payments#13]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

**Comment by casha1995** [comment]
just install :
sudo apt-get install redis-server
then run command to confirm that everything ok:
sudo service redis-server status
And the output will be: redis-server is running
