### ISSUE TITLE
TypeError: Cannot read property 'rates' of undefined

### ISSUE THREAD

**Issue by Rodrigolmti** [guerrerocarlos/bitcoin-receive-payments#4]
Hello there, i trying to use this package but when i start my server i receive that error

> TypeError: Cannot read property 'rates' of undefined
> self.fx.rates = data.rates index.js:138

i already create a key at openexchangerates and xPub key in BIP32 only for tests, these openxchangesrates is mandatory?

**Comment by invite-frey** [comment]
Same issue... Managed to get past this error by hard coding the openxchangerates app id into line 189 in index.js. Seems like it's not being set by the constructor.

**Comment by infosquatter** [comment]
@invite-frey Could you share what you did? Thanks.

**Comment by gustawdaniel** [comment]
I have the same error. I was trying to use this package with meteor. I installed it by npm and copied code from README to meteor method.

I had also problem with redis, but I installed it by sudo apt-get install redis-server and run by command redis-server.

There are some output of error:

```
W20180128-20:53:41.443(1)? (STDERR) /home/daniel/pro/btcm2/node_modules/bitcoin-receive-payments/index.js:139
W20180128-20:53:41.443(1)? (STDERR)       self.fx.rates = data.rates
W20180128-20:53:41.443(1)? (STDERR)                            ^
W20180128-20:53:41.444(1)? (STDERR) 
W20180128-20:53:41.444(1)? (STDERR) TypeError: Cannot read property 'rates' of undefined
W20180128-20:53:41.444(1)? (STDERR)     at handleCurrencies (/home/daniel/pro/btcm2/node_modules/bitcoin-receive-payments/index.js:139:28)
W20180128-20:53:41.445(1)? (STDERR)     at Request.handleResponse [as _callback] (/home/daniel/pro/btcm2/node_modules/openexchangerates-api/lib/index.js:150:7)
W20180128-20:53:41.445(1)? (STDERR)     at Request.self.callback (/home/daniel/pro/btcm2/node_modules/request/request.js:186:22)
W20180128-20:53:41.445(1)? (STDERR)     at emitTwo (events.js:126:13)
W20180128-20:53:41.445(1)? (STDERR)     at Request.emit (events.js:214:7)
W20180128-20:53:41.446(1)? (STDERR)     at Request.<anonymous> (/home/daniel/pro/btcm2/node_modules/request/request.js:1163:10)
W20180128-20:53:41.446(1)? (STDERR)     at emitOne (events.js:116:13)
W20180128-20:53:41.446(1)? (STDERR)     at Request.emit (events.js:211:7)
W20180128-20:53:41.447(1)? (STDERR)     at IncomingMessage.<anonymous> (/home/daniel/pro/btcm2/node_modules/request/request.js:1085:12)
W20180128-20:53:41.447(1)? (STDERR)     at Object.onceWrapper (events.js:313:30)
W20180128-20:53:41.447(1)? (STDERR)     at emitNone (events.js:111:20)
W20180128-20:53:41.448(1)? (STDERR)     at IncomingMessage.emit (events.js:208:7)
W20180128-20:53:41.448(1)? (STDERR)     at endReadableNT (_stream_readable.js:1055:12)
W20180128-20:53:41.448(1)? (STDERR)     at _combinedTickCallback (internal/process/next_tick.js:138:11)
W20180128-20:53:41.448(1)? (STDERR)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
