### ISSUE TITLE
error recieved creating bitcoin address

### ISSUE THREAD

**Issue by dylankilkenny** [guerrerocarlos/bitcoin-receive-payments#5]
Set up a test using the code provided in the readme and recieved the following output:

`<createAddress> 5554555 undefined`
`Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379`
 `   at Object._errnoException (util.js:1026:11)`
  `  at _exceptionWithHostPort (util.js:1049:20)`
 `   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)`
`/Users/dylankilkenny/dev/expressTesting/index.js:652`
`    throw err;`
`    ^`

any ideas on what could have went wrong?

**Comment by guerrerocarlos** [comment]
Do you have a local mongodb instance running?

**Comment by dylankilkenny** [comment]
No i do not, should i have?

**Comment by guerrerocarlos** [comment]
Oh, by the port 6379, the redis database is the one that is missing. 

Yes, you need redis to be able to run the module.

**Comment by springjben** [comment]
What do you mean I need redis to make it run?? ^

I have mongodb running in the background and I am getting a simular error:

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

**Comment by springjben** [comment]
Do I need to install redis-server separately?

**Comment by springjben** [comment]
Might be worth noting I am on Windows.

**Comment by trialforlife** [comment]
Are there any updates on this issue?
